BLUE_ShopCar = [
	["rhsusf_m998_w_2dr_fulltop", 3, [], ["Olive", "Desert"]],
	["cup_b_lr_transport_gb_w", 3, [], ["CZW", "CZS"]],
	["rhsusf_m1025_w", 3, [], ["Olive", "Desert"]],
	["rhsusf_mrzr4_d", 3, [], ["olive", "standard"]],
	["rhsusf_m1025_w_m2", 3, [], ["Olive", "Desert"]],
	["CUP_B_LR_MG_CZ_W", 5, [], ["CZW", "CZS"]],
	["rhsusf_m1043_w", 5, [], ["Olive", "standard", "Desert"]],
	["rhsusf_M1238A1_socom_d", 6, [], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_m1025_w_mk19", 9, ["FixAmmo"], ["Olive", "Desert"]],
	// ["CUP_B_nM1025_SOV_Mk19_USMC_WDL", 12, [], ["Woodland", "Desert", "NATOGreen", "NATOArid"]], 
	["CUP_B_LR_Special_CZ_W", 5, [], ["CZW", "CZS"]],
	["CUP_B_Jackal2_GMG_GB_W", 5, []],
	["rhsusf_m1151_usarmy_wd", 6, [], ["rhs_woodland", "rhs_desert", "rhs_olive"]],
	["rhsusf_m1151_m240_v2_usarmy_wd", 6, [], ["rhs_woodland", "rhs_desert", "rhs_olive"]],
	["rhsusf_m1151_m2_v2_usarmy_wd", 7, [], ["rhs_woodland", "rhs_desert", "rhs_olive"]],
	["rhsusf_m1151_mk19_v2_usarmy_wd", 9, ["FixAmmo"], ["rhs_woodland", "rhs_desert", "rhs_olive"]],
	["CUP_B_RG31_M2_USA", 10, [], ["Woodland", "Desert"]],
	["CUP_B_RG31_Mk19_USA", 9, [], ["Woodland", "Desert"]],
	["rhsusf_m1240a1_m240_usmc_wd", 9, [], ["rhs_olive", "rhs_woodland", "rhs_desert"]],
	["rhsusf_m1240a1_m2_usmc_wd", 10, [], ["rhs_olive", "rhs_woodland", "rhs_desert"]],
	["rhsusf_M1220_M2_usarmy_wd", 11, [], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_CGRCAT1A2_M2_usmc_d", 11, [], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_M1232_M2_usarmy_wd", 12, [], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_m1165a1_gmv_m134d_m240_socom_d", 11, [], ["rhs_sofwoodland", "rhs_sofdesert"]],
	["CUP_B_Dingo_CZ_Wdl", 28, [], ["CZwdl", "CZdes"]],
	["rhsusf_CGRCAT1A2_Mk19_usmc_d", 12, ["FixAmmo"], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_m1240a1_mk19_usmc_wd", 12, ["FixAmmo"], ["rhs_olive", "rhs_woodland", "rhs_desert"]],
	["rhsusf_M1220_MK19_usarmy_wd", 12, ["FixAmmo"], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_M1232_MK19_usarmy_wd", 12, ["FixAmmo"], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_M1117_W", 18, ["FixAmmo"], ["standard", "olive", "desert"]],
	["rhsusf_M1078A1P2_WD_flatbed_fmtv_usarmy", 26, ["AA", "LockCargo"], ["rhs_woodland", "rhs_desert"]],
	["CUP_B_nM1097_AVENGER_USMC_DES", 21, [], ["Woodland", "Desert", "NATOGreen", "NATOArid"]],
	["CUP_B_LAV25M240_USMC", 37, [], ["green", "NATO_woodland", "desert"]],
	["B_UGV_01_rcws_F", 26, ["FixAmmo"], ["Blufor", "Olive"]],
	["rhsusf_m1045_w", 24, ["FixAmmo"], ["Olive", "standard", "Desert"]],
	["rhsusf_m1151_m2crows_usarmy_wd", 46, [], ["rhs_olive""rhs_woodland", "rhs_desert"]],
	["CUP_B_Boxer_HMG_GER_WDL", 44, [], ["Flecktarn", "Tropentarn"]],
	["rhsusf_M1238A1_M2_socom_d", 49, [], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_m1240a1_m2crows_usmc_wd", 49, [], ["rhs_olive", "rhs_woodland", "rhs_desert"]],
	["rhsusf_M1220_M153_M2_usarmy_d", 49, [], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_stryker_m1126_m2_wd", 51, [], ["Olive", "OliveDirty", "Tan"]],
	["CUP_B_Dingo_GL_CZ_Wdl", 29, [], ["CZwdl", "CZdes"]],
	["rhsusf_m1151_mk19crows_usarmy_wd", 45, ["FixAmmo"], ["rhs_woodland", "rhs_desert", "rhs_olive"]],
	["CUP_B_Boxer_GMG_GER_WDL", 42, [], ["Flecktarn", "Tropentarn"]],
	["CUP_B_M1128_MGS_Woodland", 38, ["FixAmmo"], ["Woodland", "Desert"]],
	["rhsusf_stryker_m1126_mk19_wd", 51, ["FixAmmo"], ["Olive", "OliveDirty", "Tan"]],
	["rhsusf_M1238A1_Mk19_socom_d", 48, ["FixAmmo"], ["rhs_woodland", "rhs_desert"]],
	["rhsusf_m1240a1_mk19crows_usmc_wd", 48, ["FixAmmo"], ["rhs_olive", "rhs_woodland", "rhs_desert"]],
	["rhsusf_stryker_m1134_wd", 47, [], ["Olive", "Tan"]],
	["CUP_B_HMMWV_Crows_MK19_USA", 63, [], ["Green", "Desert"]],
	["CUP_B_M1126_ICV_MK19_Woodland", 65, [], ["Woodland", "Desert"]],
	["CUP_B_RM70_CZ", 149, []],
	["rhsusf_M142_usarmy_WD", 40, ["Atacms"], ["rhs_woodland", "rhs_usmc_woodland", "rhs_desert"]],
	["rhsusf_M142_usarmy_WD", 97, ["M31"], ["rhs_woodland", "rhs_usmc_woodland", "rhs_desert"]],
	["B_SAM_System_03_F", 35, [], ["Olive", "Desert"]],
	["B_Radar_System_01_F", 20, ["DataLinkOn"], ["Olive", "Desert"]]
];

BLUE_ShopTank = [
	["rhsusf_m113_usarmy_M240", 6, [], ["Olive", "Desert"]],
	["rhsusf_m113_usarmy", 8, [], ["Olive", "Desert"]],
	["CUP_B_FV432_GB_GPMG", 8, [], ["Olive", "Desert"]],
	["rhsusf_m113_usarmy_MK19", 7, ["FixAmmo"], ["Olive", "Desert"]],
	["CUP_B_FV432_Bulldog_GB_W", 10, [], ["Woodland", "Desert"]],
	["CUP_B_FV432_Bulldog_GB_W_RWS", 23, [], ["Woodland", "Desert"]],
	// ["rhsgref_cdf_b_zsu234", 21, ["NoRadar"], ["CDF", "rhs_sand"]], 
	["CUP_B_AAV_USMC", 31, [], ["Woodland", "RACS"]],
	["CUP_B_M163_USA", 12, ["NoRadar"], ["Green", "desert"]],
	["CUP_B_M163_USA", 22, [], ["Green", "desert"]],
	// ["rhsgref_cdf_b_zsu234", 31, [], ["CDF", "rhs_sand"]], 
	["RHS_M2A2", 40, ["FixAmmo"], ["Olive", "standard", "Desert"]],
	["rhsusf_m1a1hc_wd", 49, [], ["woodland", "desert", "OD"]],
	["RHS_M6", 32, [], ["Olive", "standard", "Desert"]],
	["rhsusf_m1a2sep1wd_usarmy", 92, [], ["woodland", "desert"]],
	["rhsusf_m1a1aimwd_usarmy", 92, [], ["woodland", "desert"]],
	["rhsusf_m1a1fep_wd", 92, [], ["woodland", "desert", "OD"]],
	["rhsusf_m1a2sep2wd_usarmy", 124, [], ["woodland", "desert"]],
	["RHS_M2A3_wd", 78, ["FixAmmo"], ["Olive", "standard", "Desert"]],
	["CUP_B_FV510_GB_W_SLAT", 43, ["FixAmmo"], ["Woodland", "Desert"]],
	["CUP_B_MCV80_GB_W_SLAT", 43, ["FixAmmo"], ["Woodland", "Desert"]],
	["B_APC_Tracked_01_AA_F", 55, ["FixTurret"], ["Sand", "Olive"]],
	["RHS_M2A2_BUSKI_WD", 55, ["FixAmmo"], ["Olive", "standard", "Desert"]],
	["RHS_M2A3_BUSKI", 93, ["FixAmmo"], ["Olive", "standard", "Desert"]],
	["rhsusf_m1a2sep1tuskiwd_usarmy", 108, [], ["woodland", "desert"]],
	["rhsusf_m1a1aim_tuski_wd", 107, [], ["woodland", "desert"]],
	["rhsusf_m1a2sep1tuskiiwd_usarmy", 113, [], ["woodland", "desert"]],
	["RHS_M2A3_BUSKIII", 103, ["FixAmmo"], ["Olive", "standard", "Desert"]],
	["rhsusf_m109_usarmy", 92, ["FixAmmo"], ["standard", "Desert"]]
];

BLUE_ShopCar + BLUE_ShopTank