RED_ShopCar = [
	["CUP_O_Hilux_unarmed_TK_INS", 3, [], ["Olive", "Grey"]],
	["CUP_O_Datsun_4seat", 3, [], ["greenBrownBeigeWoodland", "desert"]],
	["CUP_O_LR_Transport_TKA", 3, [], ["GBW", "CZD"]],
	["CUP_O_SUV_TKA", 3, []],
	["CUP_O_Datsun_PK", 4, [], ["greenBrownBeigeWoodland", "desert"]],
	["rhsgref_BRDM2_HQ_vdv", 4, [], ["olive", "3tone"]],
	["CUP_O_GAZ_Vodnik_PK_RU", 4, []],
	["CUP_O_LR_MG_TKA", 5, [], ["GBW", "CZD"]],
	["CUP_O_Hilux_DSHKM_TK_INS", 4, [], ["Olive", "Grey"]],
	["rhs_tigr_m_vdv", 6, [], ["standard", "Camo"]],
	["CUP_O_Hilux_AGS30_TK_INS", 4, [], ["Olive", "Grey"]],
	["CUP_O_GAZ_Vodnik_AGS_RU", 4, []],
	["rhs_tigr_sts_3camo_vdv", 10, [], ["standard", "Camo"]],
	["rhs_btr60_vdv", 8, [], ["standard", "3tone"]],
	["rhs_btr70_vdv", 8, [], ["standard", "Camo1", "Camo2", "rhs_sand", "Desert", "Marine", "Belarusian"]],
	["rhs_btr80_vdv", 12, [], ["standard", "tricolourhard", "tricolourparade", "rhs_sand"]],
	["rhsgref_ins_uaz_spg9", 11, [], ["standard", "Camo", "Camo2", "Camo4"]],
	["CUP_O_Kamaz_Open_RU", 23, ["AA", "LockCargo"], ["RU", "Green", "Camo1"]],
	["rhs_ural_Zu23_msv_01", 11, []],
	["CUP_O_BTR60_GREEN_RU", 24, ["FixAmmo"], ["RU_GREEN", "RU_WDL", "RU_WINTER"]],
	["Iustum_rhsgref_BRDM2_ms", 26, ["SWIFT"]],
	["rhs_btr82v_vv", 28, [], ["standard", "tricolourhard", "tricolourparade", "rhs_sand"]],
	["CUP_O_LR_AA_TKA", 24, ["FixTurret"], ["GBW", "CZD"]],
	["CUP_O_GAZ_Vodnik_BPPU_RU", 26, []],
	["rhs_btr80a_vdv", 16, [], ["standard", "rhs_sand", "tricolourhard"]],
	["rhs_btr82a_vv", 31, [], ["standard", "rhs_sand", "tricolourhard"]],
	["O_UGV_01_rcws_F", 26, ["FixAmmo"], ["Opfor", "GreenHex"]],
	["CUP_O_Hilux_metis_TK_INS", 15, [], ["Olive", "Grey"]],
	["CUP_O_BRDM2_ATGM_RUS", 28, []],
	["CUP_O_BTR90_RU", 35, []],
	["CUP_O_BM21_SLA", 143, [], ["SLA", "RU"]],
	["rhs_9k79", 49, [], ["standard", "camo"]]
];

RED_ShopTank = [
	["rhs_bmd1pk", 18, [], ["standard", "Camo1", "CDF"]],
	["rhs_bmd1r", 24, [], ["standard", "Camo1"]],
	["rhs_bmp1_msv", 19, [], ["standard", "rhs_sand"]],
	["rhs_bmd1", 19, [], ["standard", "Camo1", "CDF"]],
	["rhs_bmp1d_msv", 19, [], ["standard", "rhs_sand"]],
	["rhs_zsu234_aa", 21, ["NoRadar"], ["standard", "rhs_sand"]],
	["rhs_bmp1p_msv", 26, [], ["standard", "rhs_sand"]],
	["rhs_bmd1p", 27, [], ["standard", "Camo1", "CDF"]],
	["rhs_Ob_681_2", 28, [], ["standard", "rhs_sand", "CDF"]],
	["rhs_zsu234_aa", 31, [], ["standard", "rhs_sand"]],
	["rhs_bmp2_msv", 26, [], ["standard", "rhs_sand", "CDF"]],
	["rhs_bmp2d_msv", 26, [], ["standard", "rhs_sand", "CDF"]],
	["rhs_bmd2", 23, [], ["standard", "Desert", "Camo1", "Camo2", "Camo3", "Camo4", "CDF"]],
	["rhs_sprut_vdv", 35, []],
	["rhs_t80", 34, []],
	["rhs_t80b", 40, []],
	["rhs_t80bk", 34, []],
	["rhs_t72ba_tv", 38, [], ["standard", "rhs_Sand"]],
	["rhs_t72bb_tv", 40, [], ["standard", "rhs_Sand"]],
	["rhs_t80bv", 40, []],
	["rhs_t80bvk", 36, []],
	["rhs_t80u45m", 56, [], ["standard", "tricolor"]],
	["rhs_t80u", 47, [], ["standard", "tricolor"]],
	["rhs_t72bc_tv", 40, [], ["standard", "rhs_Sand"]],
	["rhs_t80uk", 54, [], ["standard", "tricolor"]],
	["rhs_t80um", 54, [], ["standard", "tricolor"]],
	["rhs_bmd2m", 46, [], ["standard", "Desert", "Camo1", "Camo2", "Camo3", "Camo4", "CDF"]],
	["rhs_t80a", 57, []],
	["rhs_t90_tv", 56, [], ["standard", "rhs_Sand"]],
	["rhs_bmp3_msv", 38, [], ["standard", "rhs_sand"]],
	["rhs_t72bd_tv", 60, [], ["standard", "rhs_Sand"]],
	["rhs_t90a_tv", 62, [], ["standard", "rhs_Sand"]],
	["rhs_t90saa_tv", 62, [], ["standard", "rhs_Sand"]],
	["rhs_t80ue1", 62, [], ["standard", "tricolor"]],
	["rhs_bmp3m_msv", 57, [], ["standard", "rhs_sand"]],
	["rhs_bmd4_vdv", 50, []],
	["rhs_bmd4m_vdv", 57, []],
	["rhs_bmp3mera_msv", 60, [], ["standard", "rhs_sand"]],
	["rhs_bmd4ma_vdv", 60, []],
	["O_APC_Tracked_02_AA_F", 55, ["FixTurret"], ["Green", "Hex", "GreenHex"]],
	["CUP_O_2S6M_RU", 61, []],
	["rhs_t72be_tv", 78, [], ["standard", "rhs_Sand"]],
	["rhs_t90sab_tv", 80, [], ["standard", "rhs_Sand"]],
	["rhs_t90am_tv", 108, [], ["standard", "rhs_Sand"]],
	["rhs_t90sm_tv", 108, [], ["standard", "rhs_Sand"]],
	["rhs_t14_noKAZ", 132, ["FixAmmo"]],
	["rhs_2s1_at_tv", 23, [], ["standard", "sand", "RHS_SAF_Camo", "light", "standard_dirty", "light_dirty", "CDF"]],
	["rhs_2s1_tv", 39, ["FixAmmo"], ["standard", "sand", "RHS_SAF_Camo", "light", "standard_dirty", "light_dirty", "CDF"]],
	["rhs_2s3_tv", 62, ["FixAmmo"], ["standard", "rhs_sand", "rhs_tri"]]
];

RED_ShopCar + RED_ShopTank